import boto3
import json
import uuid
import os
from datetime import datetime

healthlake = boto3.client('healthlake')

def map_entities_to_fhir(entities):
    """
    Maps the raw AI-extracted entities dictionary into a valid FHIR R4 Patient resource.
    """
    # Extract Patient Name safely
    patient_name = entities.get('PatientName', 'Unknown Patient')
    
    # Handle name splitting (First/Last)
    name_parts = patient_name.split()
    family = name_parts[-1] if len(name_parts) > 1 else patient_name
    given = name_parts[:-1] if len(name_parts) > 1 else [patient_name]

    # Create the FHIR Resource
    return {
        "resourceType": "Patient",
        "id": str(uuid.uuid4()),
        "meta": {
            "profile": ["http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"]
        },
        "text": {
            "status": "generated",
            "div": f'<div xmlns="http://www.w3.org/1999/xhtml">Generated by AI Pipeline. Raw Data: {json.dumps(entities)}</div>'
        },
        "name": [{
            "use": "official",
            "family": family,
            "given": given,
            "text": patient_name
        }],
        # Store other raw entities (Vitals, Meds) in extension or containment if needed
        # For this workshop, storing the raw dump in 'text.div' (above) is sufficient for visibility.
    }

def lambda_handler(event, context):
    # Event is LIST of results from Map State
    results = event
    
    # 1. Guardrail Check
    invalid_chunks = [r for r in results if r.get('classification') == 'INVALID']
    if invalid_chunks:
        reason = invalid_chunks[0].get('reason', 'Content flagged as INVALID')
        print(f"SECURITY BLOCK: Data contains invalid content. Reason: {reason}")
        return {"status": "REJECTED", "reason": reason}
    
    # 2. Setup Provenance/Source Info
    if results:
        metadata = results[0].get('metadata', {})
    else:
        metadata = {}
        
    source_agent = metadata.get('sender', 'Web Upload')
    print(f"Ingesting clean data verified from source: {source_agent}")
    
    # 3. Construct FHIR Entries
    entries = []
    for res in results:
        # --- FIX START: Logic to Map Entities to FHIR ---
        if 'fhir_resource' not in res and 'entities' in res:
            print("Detected raw entities. Mapping to FHIR Patient resource...")
            res['fhir_resource'] = map_entities_to_fhir(res['entities'])
        # --- FIX END ---

        if 'fhir_resource' in res:
            entries.append({
                "resource": res['fhir_resource'],
                "request": {
                    "method": "POST",
                    "url": res['fhir_resource']['resourceType']
                }
            })

    if not entries:
        print("No valid FHIR resources found to ingest.")
        return {"status": "SKIPPED", "reason": "No entities extracted"}

    # 4. ACTUAL WRITE TO HEALTHLAKE
    try:
        success_count = 0
        for entry in entries:
            # Using create_resource loop for workshop reliability
            healthlake.create_resource(
                DatastoreId=os.environ['HEALTHLAKE_ID'],
                Resource=json.dumps(entry['resource'])
            )
            success_count += 1
            
        print(f"Successfully ingested {success_count} resources into HealthLake.")
        
    except Exception as e:
        print(f"Error writing to HealthLake: {str(e)}")
        raise e
    
    return {"status": "SUCCESS", "items_processed": success_count}
